steps:
  - name: 'gcr.io/cloud-builders/composer'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/composer'
    args: ['global', 'require', 'laravel/pint']
  - name: 'gcr.io/cloud-builders/composer'
    args: ['pint', '--test']
  - name: 'gcr.io/cloud-builders/php'
    args: ['artisan', 'test']

options:
  env:
    - 'DB_CONNECTION=mysql'
    - 'DB_HOST=127.0.0.1'
    - 'DB_PORT=3306'
    - 'DB_DATABASE=wellfish_test'
    - 'DB_USERNAME=root'
    - 'DB_PASSWORD=root'

