steps:
  # Step 2: Install Composer dependencies
  - name: 'composer:latest'
    args: ['install']

  # Step 6: Run Pint lint check
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

  # Step 5: Run PHPUnit tests
  - name: 'php:8.2-mysql'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/phpunit

# Specify the timeout
timeout: '1200s'
