steps:
  # Step 0: Install Composer dependencies
  - name: 'composer:latest'
    args: ['install']

  # Step 1: Create the .env and .env.testing files
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp .env.example .env.testing
        php artisan key:generate --env=testing
        echo "APP_ENV=testing" >> .env.testing
        echo "DB_HOST=$$DB_HOST_STAGING_TEST" >> .env.testing
        echo "DB_DATABASE=wellfish_test" >> .env.testing
        echo "DB_USERNAME=root" >> .env.testing
        echo "DB_PASSWORD=$$DB_PASSWORD_STAGING_TEST" >> .env.testing
        ls -la

  # Step 2: Run Pint lint check
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

  # Step 3: Run the PHPUnit tests
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev libzip-dev unzip
        docker-php-ext-install pdo pdo_mysql gd zip bcmath
        vendor/bin/phpunit

# Specify the timeout
timeout: '1200s'
