steps:
  # Step 0: Install Composer dependencies
  - name: 'composer:latest'
    args: ['install']

  # Step 1: Run Pint lint check
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

  # Step 2 (new): Install MySQL client and run the database setup script
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt update
        apt install -y mysql-client
        ./dbFile/dev_sh.sh ./dbFile/dev.sql

  # Step 3: Run the PHPUnit tests
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/phpunit

# Specify the timeout
timeout: '1200s'
