steps:
  # Step 0: Set up PHP and Composer
  - id: 'Install PHP and composer'
    name: 'php'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Composer
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

  # Step 1: Install Composer dependencies
  - id: 'Install Composer dependencies'
    name: 'composer'
    args: ['install']

  # Step 5: Run Pint lint check
  - id: 'Run Pint lint check'
    name: 'php'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

  # Step 2: Set up the database
  - id: 'Set up MySql'
    name: 'mysql'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize MySQL data directory
        mysqld --initialize-insecure --user=mysql --datadir=/var/lib/mysql
        # Start MySQL service
        mysqld --user=mysql --datadir=/var/lib/mysql --skip-networking &
        # Set root user password
        mysqladmin -u root password 'root'

  # Step 3: Create the test database
  - id: 'Create the database'
    name: 'mysql'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sleep 10 # Give MySQL some time to start
        mysql -u root -p root -e "CREATE DATABASE wellfish_test;"
    waitFor:
      - 'Set up MySql'

  # Step 4: Run PHPUnit tests
  - id: 'Run tests'
    name: 'php'
    entrypoint: 'bash'
    env:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=wellfish_test
      - DB_USERNAME=root
      - DB_PASSWORD=root
    args:
      - '-c'
      - |
        vendor/bin/phpunit

# Specify the timeout
timeout: '1200s'
