steps:
  # Step 1: Set up PHP and Composer
  - name: 'php:8.1-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Composer
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

  # Step 2: Install Composer dependencies
  - name: 'composer:latest'
    args: ['install']

  # Step 3: Start MySQL server
  - name: 'mysql:latest'
    id: 'start-mysql'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Start MySQL server with a password for root user
        docker-entrypoint.sh mysqld --user=mysql --datadir=/var/lib/mysql --skip-networking &
        sleep 10
        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';" -p
        mysqladmin -u root -proot shutdown
        mysqld --user=mysql --datadir=/var/lib/mysql --skip-networking &
        # Wait for MySQL server to be available
        for i in {30..0}; do
          if echo 'SELECT 1' | mysql -u root -proot --protocol=socket -h localhost; then
            break
          fi
          echo 'MySQL init process in progress...'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo >&2 'MySQL init process failed.'
          exit 1
        fi

  # Step 4: Create the test database
  - name: 'mysql:latest'
    waitFor: ['start-mysql']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mysql -u root -proot -e "CREATE DATABASE wellfish_test;"

  # Step 5: Run database migrations
  - name: 'php:8.1-cli'
    entrypoint: 'bash'
    waitFor: ['start-mysql']
    env:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=wellfish_test
      - DB_USERNAME=root
      - DB_PASSWORD=root
    args:
      - '-c'
      - |
        cp .env.testing .env
        php artisan migrate --env=testing

  # Step 6: Run PHPUnit tests
  - name: 'php:8.1-cli'
    entrypoint: 'bash'
    waitFor: ['start-mysql']
    env:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=wellfish_test
      - DB_USERNAME=root
      - DB_PASSWORD=root
    args:
      - '-c'
      - |
        vendor/bin/phpunit

  # Step 7: Run Pint lint check
  - name: 'php:8.1-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

# Specify the timeout
timeout: '1200s'
