steps:
  # Step 0: Install Composer dependencies
  - id: 'Install dependencies'
    name: 'composer:latest'
    args: ['install']

  # Step 1: Create the .env.testing files
  - id: 'Create setup env testing file'
    name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp .env.example .env.testing
        php artisan key:generate --env=testing
        sed -i "s/^APP_ENV=.*/APP_ENV=testing/" .env.testing
        sed -i "s/^DB_HOST=.*/DB_HOST=$$DB_HOST_ST/" .env.testing
        sed -i "s/^DB_DATABASE=.*/DB_DATABASE=wellfish_test/" .env.testing
        sed -i "s/^DB_USERNAME=.*/DB_USERNAME=root/" .env.testing
        sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=$$DB_PASSWORD_ST/" .env.testing
        sed -i "s/^FILESYSTEM_DRIVER=.*/FILESYSTEM_DRIVER=gcs/" .env.testing
        sed -i "s/^GOOGLE_CLOUD_STORAGE_BUCKET=.*/GOOGLE_CLOUD_STORAGE_BUCKET=wellfish-profile-picture-staging/" .env.testing
        sed -i "s/^GOOGLE_CLOUD_PROJECT_ID=.*/GOOGLE_CLOUD_PROJECT_ID=wellfish/" .env.testing
        # ls -la
        # cat .env.testing
    secretEnv: [
        'DB_HOST_ST',
        'DB_PASSWORD_ST'
    ]

  # Step 2: Run Pint lint check
  - id: 'Check Code style using Pint'
    name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

  #TODO : Fix masalah connect ke mysql instance ini kalau mysql instance nya gk ngasih network 0.0.0.0/0 dia gk mau ke connect
  #TODO: bikin image untuk phpnya biar gk perlu install2 lagi
  # Step 3: Run the PHPUnit tests
  - id: 'Run PHPUnit tests'
    name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev libzip-dev unzip
        docker-php-ext-install pdo pdo_mysql gd zip bcmath
        # install gd
        docker-php-ext-configure gd --enable-gd --with-jpeg
        docker-php-ext-install gd
        vendor/bin/phpunit

  # Step 4: Deploy to Compute Engine via SSH
  - id: 'Deploy to Compute engine via ssh'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh backend-api-staging --zone=asia-southeast2-b --command="cd /var/www/backend
        && sudo chown -R $USER:$USER /var/www
        && git pull
        && php artisan migrate
        && php artisan db:seed
        && php artisan config:cache
        && php artisan route:cache
        && php artisan view:cache"

# Specify the timeout
timeout: '1200s'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MYSQL_HOST_STAGING/versions/latest
      env: 'DB_HOST_ST'
    - versionName: projects/$PROJECT_ID/secrets/MYSQL_PASSWORD_STAGING/versions/latest
      env: 'DB_PASSWORD_ST'
