steps:
  # Step 1: Install Composer dependencies
  - name: 'composer:latest'
    args: ['install']

  # Step 2: Run Pint lint check
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        vendor/bin/pint --test

  # Install Cloud SQL proxy
  - id: proxy-install
    name: 'php:8.2-cli'
    entrypoint: sh
    args:
      - "-c"
      - "wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.4.0/cloud-sql-proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy"

  # Step 3: Run PHPUnit tests
  - name: 'php:8.2-cli'
    entrypoint: 'bash'
    args:
      - "-c"
      - "mkdir /cloudsql; chmod 777 /cloudsql; (./cloud_sql_proxy --unix-socket /cloudsql 34.128.73.78 & sleep 2) && vendor/bin/phpunit"

# Specify the timeout
timeout: '1200s'
